# Generated by Django 4.1.1 on 2022-10-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_auto_20220912_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True,
                                      primary_key=True,
                                      serialize=False,
                                      verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(auto_created=True,
                                      primary_key=True,
                                      serialize=False,
                                      verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='id',
            field=models.BigAutoField(auto_created=True,
                                      primary_key=True,
                                      serialize=False,
                                      verbose_name='ID'),
        ),
    ]
