name: Django Testing and Deploy

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check updates
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Linting
        run: flake8 logistic

      - name: Testing
        run: python manage.py test